###
Simulation:
  mcts_simulations: 300
  keep_subtree: True

###
UCT:
  pb_c_base: 10000
  pb_c_init: 1.15

###
Exploration:
  number_of_softmax_moves: 15
  epsilon_softmax_exploration: 0.04
  epsilon_random_exploration: 0.003
  value_factor: 1
  root_exploration_destribution: gamma
  root_exploration_fraction: 0.20
  dist_alpha: 0.15
  dist_beta: 1
