###
Simulation:
  mcts_simulations: 50
  keep_subtree: True

###
UCT:
  pb_c_base: 10000
  pb_c_init: 1.15

###
Exploration:
  value_factor: 1
  number_of_softmax_moves: 0
  epsilon_softmax_exploration: 0.04
  epsilon_random_exploration: 0.001
  root_exploration_destribution: gamma
  root_exploration_fraction: 0.20
  dist_alpha: 0.15
  dist_beta: 1
