###
Initialization:
  network_name: test_net
  load_checkpoint: True

  Checkpoint:
    cp_network_name: checkpoint_net
    iteration_number: 2000
    keep_optimizer: True
    keep_scheduler: False
    fresh_start: False


###
Running:
  running_mode: sequential
  num_actors: 3
  early_fill_per_type: 1200
  early_softmax_moves: 12
  early_softmax_exploration: 0.5
  early_random_exploration: 0.5
  training_steps: 5000

  Sequential:
    num_games_per_type_per_step: 12

  Asynchronous:
    update_delay : 120


###
Cache:
  cache_choice: keyless
  max_size: 8000
  keep_updated: True


###
Saving:
  storage_frequency: 1
  save_frequency: 20


###
Testing:
  asynchronous_testing: True
  testing_actors: 1
  early_testing: False
  policy_test_frequency: 25
  mcts_test_frequency: 65
  num_policy_test_games: 100
  num_mcts_test_games: 100
  test_game_index: 0


###
Plotting:
  plot_loss: True
  plot_weights: False
  plot_frequency: 10
  value_split: 200
  policy_split: 200
  combined_split: 200


###
Recurrent Options:
  train_iterations: [6]
  pred_iterations: [6]
  test_iterations: 6
  alpha: 0.01
  

###
Learning:
  shared_storage_size: 3
  replay_window_size: 10000
  batch_extraction: local
  value_loss: SE
  policy_loss: CEL
  normalize_cel: False
  learning_method: samples

  Samples:
    batch_size: 256
    num_samples: 32
    with_replacement: True
    late_heavy: True

  Epochs:
    batch_size: 2048
    learning_epochs: 1
    plot_epochs: False


###
Optimizer:
  optimizer_choice: Adam

  SGD:
    weight_decay: 1.0e-07
    momentum: 0.9
    nesterov: True


###
Scheduler:
  learning_rate: 1.0e-6
  scheduler_boundaries: [30000, 60000, 90000]
  scheduler_gamma: 0.2