###
Simulation:
  mcts_simulations: 150
  keep_subtree: True

###
UCT:
  pb_c_base: 8000
  pb_c_init: 1.15

###
Exploration:
  value_factor: 1
  number_of_softmax_moves: 12
  epsilon_softmax_exploration: 0.03
  epsilon_random_exploration: 0.002
  root_exploration_distribution: gamma
  root_exploration_fraction: 0.15
  root_dist_alpha: 0.15
  root_dist_beta: 1
