###
Simulation:
  mcts_simulations: 300
  keep_subtree: True

###
UCT:
  pb_c_base: 11000
  pb_c_init: 1.25

###
Exploration:
  number_of_softmax_moves: 0
  epsilon_softmax_exploration: 0.04
  epsilon_random_exploration: 0.0
  value_factor: 1
  root_exploration_distribution: gamma
  root_exploration_fraction: 0.25
  root_dist_alpha: 0.2
  root_dist_beta: 1
