###
Initialization:
  network_name: test_net_load
  load_checkpoint: True

  Checkpoint:
    cp_network_name: test_net_load
    iteration_number: "auto"
    keep_optimizer: True
    keep_scheduler: True
    load_buffer: True
    fresh_start: False
    new_plots: False

###
Running:
  running_mode: sequential
  num_actors: 4
  early_fill_per_type: 0
  early_softmax_moves: 0
  early_softmax_exploration: 0.5
  early_random_exploration: 0.5
  training_steps: 2000

  Sequential:
    num_games_per_type_per_step: 16

  Asynchronous:
    update_delay : 120


###
Cache:
  cache_choice: keyless
  max_size: 2000
  keep_updated: False


###
Saving:
  save_frequency: 10
  storage_frequency: 1
  save_buffer: True

###
Testing:
  asynchronous_testing: True
  testing_actors: 1
  early_testing: True
  policy_test_frequency: 37
  mcts_test_frequency: 91
  num_policy_test_games: 100
  num_mcts_test_games: 100
  test_game_index: 0


###
Plotting:
  plot_frequency: 5
  plot_loss: True
  plot_weights: False
  value_split: 0
  policy_split: 0
  combined_split: 0


###
Recurrent Options:
  train_iterations: [8]
  pred_iterations: [8]
  test_iterations: 8
  alpha: 0.0
  

###
Learning:
  shared_storage_size: 2
  replay_window_size: 7000
  batch_extraction: remote
  value_loss: SE
  policy_loss: CEL
  normalize_cel: True
  learning_method: samples

  Samples:
    batch_size: 256
    num_samples: 32
    with_replacement: True
    late_heavy: True

  Epochs:
    batch_size: 2048
    learning_epochs: 1
    plot_epochs: False


###
Optimizer:
  optimizer_choice: Adam

  SGD:
    weight_decay: 1.0e-07
    momentum: 0.9
    nesterov: True


###
Scheduler:
  starting_lr: 2.0e-4
  scheduler_boundaries: [3000, 6000, 20000]
  scheduler_gamma: 0.5