###
Initialization:
  network_name: short_training_test
  load_checkpoint: False

  Checkpoint:
    cp_network_name: short_training_test
    iteration_number: auto
    keep_optimizer: True
    keep_scheduler: True
    load_buffer: True
    fresh_start: False
    new_plots: False

###
Running:
  running_mode: sequential
  num_actors: 4
  early_fill_per_type: 12
  early_softmax_moves: 0
  early_softmax_exploration: 0.5
  early_random_exploration: 0.5
  training_steps: 50

  Sequential:
    num_games_per_type_per_step: 12

  Asynchronous:
    update_delay: 120


###
Cache:
  cache_choice: keyless
  max_size: 600
  keep_updated: False


###
Saving:
  save_frequency: 4
  storage_frequency: 1
  save_buffer: True

###
Testing:
  asynchronous_testing: True
  testing_actors: 1
  early_testing: False
  policy_test_frequency: 3
  mcts_test_frequency: 13
  num_policy_test_games: 20
  num_mcts_test_games: 10
  test_game_index: 0


###
Plotting:
  plot_frequency: 1
  plot_loss: True
  plot_weights: False
  recent_steps_loss: 5



###
Recurrent Options:
  train_iterations: [10]
  pred_iterations: [10]
  test_iterations: 10
  alpha: 0.0


###
Learning:
  shared_storage_size: 2
  replay_window_size: 1000
  batch_extraction: remote
  value_loss: SE
  policy_loss: CEL
  normalize_cel: False
  learning_method: samples

  Samples:
    batch_size: 16
    num_samples: 128
    with_replacement: True
    late_heavy: True

  Epochs:
    batch_size: 2048
    learning_epochs: 1
    plot_epochs: False


###
Optimizer:
  optimizer_choice: Adam

  SGD:
    weight_decay: 1.0e-07
    momentum: 0.9
    nesterov: False


###
Scheduler:
  starting_lr: 2.0e-03
  scheduler_boundaries: [10000000]
  scheduler_gamma: 0.5
