###
Testers:
  new_testers: True
  num_testers: 4
  slow: False
  print: False
  render: disabled


###
Runs:
  num_runs: 1
  num_games_per_run: 100


###
Agents:
  p1_agent:
    agent_type: mcts

    search_config_path: Configs/Search/test_search_config.yaml
    
    Cache:
      cache_choice: keyless
      max_size: 2000
      keep_updated: False

    Networks:
      load_checkpoints: True

      Checkpoints:
        cp_network_name: test_net_load

        Checkpoint range:
          first: 1
          last: 5
          step: 1

      Recurrent range:
        first: 1
        last: 5
        step: 1


  p2_agent:
    agent_type: random




