###
Testers:
  new_testers: True
  num_testers: 4
  slow: False
  print: False
  render: disabled


###
Test:
  changing_agent: 1
  changing_parameter:
    name: checkpoints # checkpoints | iterations | none
    Range:
      first: 1000
      last: 1200
      step: 10

  num_runs: 1
  num_games_per_run: 100


###
Agents:
  p1_agent:
    agent_type: mcts

    search_config_path: Configs/Search/test_search_config.yaml
    
    Cache:
      cache_choice: keyless
      max_size: 2000
      keep_updated: False

    Network:
      recurrent_iterations: 6
      load_checkpoint: True

      Checkpoint:
        cp_network_name: test_net_load
        cp_number: 1000

  p2_agent:
    agent_type: random




