###
Test:
  test_type: data # visual | data

  Data:
    Variable:
      changing_agent: 1
      changing_parameter:
        name: iterations # checkpoints | iterations | none
        Range:
          first: 4
          last: 12
          step: 1
    Runs:
      num_runs: 1
      num_games_per_run: 100

    Testers:
      new_testers: True
      num_testers: 4

###
Agents:
  p1_agent:
    agent_type: policy

    #search_config_path: Configs/Search/test_search_config.yaml
    
    Cache:
      cache_choice: keyless
      max_size: 2000
      keep_updated: False

    Network:
      recurrent_iterations: 6
      load_checkpoint: True

      Checkpoint:
        cp_network_name: test_net_load
        cp_number: 1000

  p2_agent:
    agent_type: random




