###
Initialization:
  network_name: placeholder
  load_checkpoint: False

  Checkpoint:
    cp_network_name: placeholder
    iteration_number: auto
    keep_optimizer: True
    keep_scheduler: True
    load_buffer: False
    fresh_start: False
    new_plots: False

###
Running:
  running_mode: sequential
  num_actors: 3
  early_fill_per_type: 0
  early_softmax_moves: 2
  early_softmax_exploration: 0.0
  early_random_exploration: 0.0
  training_steps: 2500

  Sequential:
    num_games_per_type_per_step: 12

  Asynchronous:
    update_delay : 120


###
Cache:
  cache_choice: keyless
  max_size: 2000
  keep_updated: False


###
Saving:
  save_frequency: 20
  storage_frequency: 1
  save_buffer: True

###
Testing:
  asynchronous_testing: True
  testing_actors: 1
  early_testing: False
  policy_test_frequency: 37
  mcts_test_frequency: 71
  num_policy_test_games: 100
  num_mcts_test_games: 100
  test_game_index: 0


###
Plotting:
  plot_frequency: 5
  plot_loss: True
  plot_weights: False
  value_split: 0
  policy_split: 0
  combined_split: 0


###
Recurrent Options:
  train_iterations: [10]
  pred_iterations: [10]
  test_iterations: 10
  alpha: 0.0
  

###
Learning:
  shared_storage_size: 2
  replay_window_size: 13000
  batch_extraction: remote
  value_loss: SE
  policy_loss: CEL
  normalize_cel: True
  learning_method: samples

  Samples:
    batch_size: 32
    num_samples: 64
    with_replacement: False
    late_heavy: True

  Epochs:
    batch_size: 2048
    learning_epochs: 1
    plot_epochs: False


###
Optimizer:
  optimizer_choice: SGD

  SGD:
    weight_decay: 0
    momentum: 0
    nesterov: False


###
Scheduler:
  starting_lr: 2.0e-05
  scheduler_boundaries: [999999999999]
  scheduler_gamma: 0.99999