---
Name: Important battle

###
Board_dimensions:
  rows: 5
  columns: 5

###
Turns: 7

###
Units:
  Soldier:
    id: 1
    attack: 1
    defense: 1
    movement: 2
    image_path: "SCS/Images/soldier.jpg"

  Tank:
    id: 2
    attack: 2
    defense: 2
    movement: 4
    image_path: "SCS/Images/tank.jpg"

###
Reinforcements:
  p1: [[1,1,1], [], [], [], [], [], []]

  p2: [[2], [], [], [], [], [], []]

###
Terrain:
  Swamp:
    id: 1
    attack_modifier: 0.5
    defense_modifier: 1
    cost: 2
    image_path: SCS/Images/swap.jpg

  Mountain:
    id: 2
    attack_modifier: 1
    defense_modifier: 2
    cost: 2
    image_path: SCS/Images/mountain.jpg

  Plains:
    id: 3
    attack_modifier: 1
    defense_modifier: 1
    cost: 1
    image_path: SCS/Images/plains.jpg

  Bush:
    id: 4
    attack_modifier: 2
    defense_modifier: 1
    cost: 1
    image_path: SCS/Images/bush.jpg

###
Map:
  creation_method: Detailed # Detailed | Randomized
  map_configuration : []

###
Victory_points:
  creation_method: Detailed # Detailed | Randomized
  vp_locations:
    p1: [[1,1]]             # YAML safe_loader does not suport tuples,
    p2: [[3,3]]             # define the points as list instead.