---
Name: Allies vs Axis

###
Board_dimensions:
  rows: 7
  columns: 7


###
Turns: 9


###
Stacking_limit: 3


###
Units:
  Ally_Soldier:
    id: 1
    attack: 1
    defense: 2
    movement: 2
    image_path: SCS/Images/ally_soldier.jpg

  Ally_Tank:
    id: 2
    attack: 2
    defense: 2
    movement: 4
    image_path: SCS/Images/ally_tank.jpg


  Axis_Soldier:
    id: 3
    attack: 1
    defense: 1
    movement: 3
    image_path: SCS/Images/axis_soldier.jpg

  Axis_Tank:
    id: 4
    attack: 4
    defense: 6
    movement: 1
    image_path: SCS/Images/axis_tank.jpg


###
Reinforcements:
  schedule:
    p1: [ [1,1,2], [], [1,1,2], [1,1,2], [1,1,2], [], [], [1,1], [], [2,2] ]

    p2: [ [4], [], [], [3,3,3,3,3,3], [], [4], [], [], [], [] ]

  arrival:
    method: Default  # Default | Detailed


###
Terrain:
  Plains:
    id: 1
    attack_modifier: 1
    defense_modifier: 1
    cost: 1
    image_path: SCS/Images/plains.jpg

  Hill:
    id: 2
    attack_modifier: 0.5
    defense_modifier: 1
    cost: 2
    image_path: SCS/Images/hill.jpg

  Mountain:
    id: 3
    attack_modifier: 1
    defense_modifier: 2
    cost: 2
    image_path: SCS/Images/mountain.jpg

  Forest:
    id: 4
    attack_modifier: 2
    defense_modifier: 1
    cost: 1
    image_path: SCS/Images/forest.jpg


###
Map:
  creation_method: Detailed # Detailed | Randomized
  map_configuration : [ [1,1,1,1,4,4,1],
                        [1,1,1,1,4,4,1],
                        [1,1,1,1,4,4,1],
                        [1,1,1,2,4,4,1],
                        [1,1,1,3,1,1,1],
                        [1,1,2,3,3,1,1],
                        [1,2,2,3,3,3,1] ]


###
Victory_points:
  creation_method: Detailed # Detailed | Randomized
  vp_locations:             
    p1: [[1,0]]     # The point coordenates are given as indexes,        
    p2: [[4,6]]     # Meaning that [0,0] will be the top left corner of the map

  # YAML safe_loader does not suport tuples,
  # define the points as two element lists instead.