---
Name: Important battle

###
Board_dimensions:
  rows: 10
  columns: 10


###
Turns: 7


###
Stacking_limit: 2


###
Units:
  Soldier:
    id: 1
    attack: 1
    defense: 1
    movement: 2
    image_path: "SCS/Images/soldier.png"


###
Reinforcements:
  schedule:
    p1: [ [1], [], [], [], [], [], [], [] ]

    p2: [ [1,1], [], [], [], [], [], [], [] ]

  arrival:
    method: Default  # Default | Detailed


###
Terrain:
  Plains:
    id: 1
    attack_modifier: 1
    defense_modifier: 1
    cost: 1
    image_path: SCS/Images/plains.jpg

  Swamp:
    id: 2
    attack_modifier: 0.5
    defense_modifier: 1
    cost: 2
    image_path: SCS/Images/swamp.jpg

  Mountain:
    id: 3
    attack_modifier: 1
    defense_modifier: 2
    cost: 2
    image_path: SCS/Images/mountain.jpg

  Bush:
    id: 4
    attack_modifier: 2
    defense_modifier: 1
    cost: 1
    image_path: SCS/Images/plains_with_bush.jpg


###
Map:
  creation_method: Detailed # Detailed | Randomized
  map_configuration : [ [1,3,4,1,1,1,1,1,1,1],
                        [1,3,2,1,1,1,1,1,1,1],
                        [1,3,1,1,1,1,1,1,1,1],
                        [1,3,1,1,1,1,1,1,1,1],
                        [1,3,1,1,1,1,1,1,1,1],
                        [1,1,1,1,1,1,1,1,1,1],
                        [1,1,1,1,1,1,1,1,1,1],
                        [1,1,1,1,1,1,1,1,1,1],
                        [1,1,1,1,1,1,1,1,1,1],
                        [1,1,1,1,1,1,1,1,1,1]   ]

###
Victory_points:
  creation_method: Detailed # Detailed | Randomized
  vp_locations:             
    p1: [[3,0]]     # The point coordenates are given as indexes,        
    p2: [[8,9]]     # Meaning that [0,0] will be the top left corner of the map

  # YAML safe_loader does not suport tuples,
  # define the points as two element lists instead.